services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - workdir=.
    ports:
      - 8080:8080
    environment:
      ENV: local
      PORT: 8080
    volumes:
      - ./:/app
    restart: always
