services:
  app:
    container_name: app
    build:
      context: .
      dockerfile_inline: |
        FROM golang:1.26-alpine
        WORKDIR /app
        RUN go install github.com/air-verse/air@latest
        ARG workdir
        WORKDIR /app/$${workdir}
      args:
        - workdir=.
    command: ["air"]
    ports:
      - 8080:8080
    environment:
      ENV: local
      PORT: 8080
    volumes:
      - ./:/app
      - ${HOME}/go/pkg/mod:/go/pkg/mod
    restart: always
